#index:
#    path: /
#    controller: App\Controller\DefaultController::index

get_blog:
    path: /blog
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\BlogController::myfunc